# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme: "minimal-mistakes-jekyll"
theme: jekyll-agency
# remote_theme: raviriley/agency-jekyll-theme
# minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# logo:
#   # path: "../img/logo.jpg"
#   path: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1920px-Image_created_with_a_mobile_phone.png"

title: "Playful Progressions"
email:
description: "Learnings from an Occupational Therapist and mother"
author: "Maria O'Farrell"

logo: #optional, defaults to site title
  path: assets\img\logo2.png
  height: 52 #height in px, defaults to 52px

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown
# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
# formspree_form_path: "f/a_form_id"
